fix: CLIN-2361 fix title cases
Ferlab-Ste-Justine/clin-fhir pull request #102
Opened 2024-05-27 13:32 UTC by meek0

2024-05-29 14:51 UTC, kstonge requested changes

2024-05-29 14:51 UTC, kstonge commented on site_root/input/resources/terminology/CodeSystem-analysis-request-code.json
> +      "display": "Global Developmental Delay / Intellectual Disabilty (Trio)",
Typo: Il manque un "i". J'ai corrigé cette typo dans Notion aussi.

2024-05-29 14:51 UTC, kstonge commented on site_root/input/resources/terminology/CodeSystem-cgh-abnormalities.json
> +      "display": "CNVs not Explaining Phenotypes",
Ne fait pas parti du ticket et n'est pas conforme à la [spécification](https://docs.google.com/spreadsheets/d/1ZKci0PabcR1EYSTiMdbr-VRZKMQO3cOGXuoma_unuCo/edit#gid=1142343953).
Retirer tout ce qui ne fait pas parti des requis du ticket [CLIN-2361](https://ferlab-crsj.atlassian.net/browse/CLIN-2361).
J'arrête ma révision ici.

2024-05-29 18:14 UTC, meek0 commented on site_root/input/resources/terminology/CodeSystem-cgh-abnormalities.json
> +      "display": "CNVs not Explaining Phenotypes",
Si je comprends bien "panels" c'est seulement "analysis request code"?

2024-05-29 18:15 UTC, meek0 commented on site_root/input/resources/terminology/CodeSystem-analysis-request-code.json
> +      "display": "Global Developmental Delay / Intellectual Disabilty (Trio)",
done

2024-06-10 12:32 UTC, kstonge approved these changes

2024-06-10 12:39 UTC, merged