new codesystems for sequencingrequest
Ferlab-Ste-Justine/clin-fhir pull request #86
Opened 2023-05-02 14:46 UTC by vferretti

2023-05-10 15:35 UTC, creativeyann17 requested changes

2023-05-10 15:35 UTC, creativeyann17 commented on site_root/input/resources/terminology/CodeSystem-sequencing-request-code.json
> +    "id": "analysis-request-code",
typo

2023-05-10 15:35 UTC, creativeyann17 commented on site_root/input/resources/terminology/ValueSet-sequencing-request-code.json
> +    "id": "analysis-request-code",
typo

2023-05-10 15:35 UTC, creativeyann17 commented on site_root/input/resources/terminology/CodeSystem-sequencing-request-code.json
> +    "url": "http://fhir.cqgc.ferlab.bio/CodeSystem/sequencing-request-code",
A rajouter dans `site_root/input/resources/profiles/StructureDefinition-cqgc-sequencing-request.json` En plus du `http://fhir.cqgc.ferlab.bio/ValueSet/analysis-request-code` ?

2023-05-11 16:05 UTC, kstonge commented on site_root/input/resources/terminology/CodeSystem-analysis-request-code.json
> +      "display": "Tumoral Transcriptome",
Dans le document [Spécification finale de la feuille Nanuq](https://www.notion.so/ferlab/Sp-cification-finale-de-la-feuille-Nanuq-ac98ca16a1fc46638a60ae3cfc9b1f2e), le nom pour TRATU est "Tumoral Transcriptome"/"Transcriptome tumoral".
Corriger ici ou le document.

2023-05-11 16:05 UTC, kstonge commented on site_root/input/resources/terminology/CodeSystem-analysis-request-code.json
> +      "display": "Tumoral Exome",
Mettre à jour le document [Spécification finale de la feuille Nanuq](https://www.notion.so/ferlab/Sp-cification-finale-de-la-feuille-Nanuq-ac98ca16a1fc46638a60ae3cfc9b1f2e) pour être cohérent avec l'implémentation.

2023-05-16 11:29 UTC, vferretti commented on site_root/input/resources/terminology/ValueSet-sequencing-request-code.json
> +    "id": "analysis-request-code",
corrigé

2023-05-16 11:30 UTC, vferretti commented on site_root/input/resources/terminology/CodeSystem-sequencing-request-code.json
> +    "url": "http://fhir.cqgc.ferlab.bio/CodeSystem/sequencing-request-code",
Je ne sais pas si c'est ca qu'il fallait faire mais j'ai ajouté dans le ValueSet le analysis-request-code.
"compose": {
      "include": [
        {
          "system": "http://fhir.cqgc.ferlab.bio/CodeSystem/sequencing-request-code"
        },
        {
          "system": "http://fhir.cqgc.ferlab.bio/CodeSystem/analysis-request-code"
        }
      ]
    }

2023-05-16 11:55 UTC, vferretti commented on site_root/input/resources/terminology/CodeSystem-analysis-request-code.json
> +      "display": "Tumoral Exome",
feuille nanuq corrigée

2023-05-25 14:35 UTC, creativeyann17 submitted a review, later dismissed

2023-05-29 16:00 UTC, creativeyann17 commented on site_root/input/resources/terminology/CodeSystem-sequencing-request-code.json
> +    "url": "http://fhir.cqgc.ferlab.bio/CodeSystem/sequencing-request-code",
Test en local concluant reussi a submit une sequencing-request avec ceci:

```
    "code": {
        "coding": [
            {
                "system": "http://fhir.cqgc.ferlab.bio/CodeSystem/analysis-request-code",
                "code": "MMG",
                "display": "Global Muscular diseases (Global Panel)"
            },
            {
                "system": "http://fhir.cqgc.ferlab.bio/CodeSystem/sequencing-request-code",
                "code": "65241",
                "display": "Tumoral Exome Sequencing"
            }
        ]
    },
```
Ca s'annonce bien

2023-05-29 20:57 UTC, creativeyann17 approved these changes

2023-05-30 18:02 UTC, merged